spring:
  profiles: default
  application:
    name: backend-service
  datasource:
    url: jdbc:postgresql://restapidemo.c85feaoxu2r3.ap-south-1.rds.amazonaws.com:5432/restapidemo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
server:
  port: 8585
